branches:
  only:
    - 4.0
    - /^feature-.*$/
language: php
php:
  - 5.3
  - 5.4
  - 5.5
notifications:
  email: false
addons:
  sauce_connect:
    username:
      secure: "B9VRUWYj0GeV3bqiR6Pzs89LVwuYgrsXCeUeIY6D6YPfceD+OgjsgnuescDdUXOA12CUt075iP37IXuWOHVesx3T8BOQllltu/mXoi/tubOAnjAzaqHbgCvbSHjltTHAmZWqlghUu1jEJBHmVjV6qyq/fWPiyUL83xvv8esgod8="
    access_key:
      secure: "Y0lQJ4iR8X17+hcAA3K3FaZAenX09phbBibLZg3ey+OPCloLe3Rbvjl3Gfk2CfZP/utK6jnjFcEY71mqxmdDxE0KBECfx5ORp0OzGDODaAE9qAzqWwsS6DlGv0t6X8B31S9GyBJVBdL28ALkJYyKxANI0UTXUmavzlrSaIGzL80="
before_script:
  - mysql -e 'create database ip_test;'
  - sed -e 's/\[\[\[\[database\]\]\]\]/ip_test/g' < Ip/Internal/Install/sql/structure.sql | sed -e 's/`ip_cms_/`ip_/g' | mysql -D ip_test # replace ip_cms_ and [[[[database]]]]
  - sed -e 's/`ip_cms_/`ip_/g' < Ip/Internal/Install/sql/data.sql | mysql -D ip_test # replace ip_cms_ to ip_
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u travis # ImpressPages does not allow empty db password
  - cd phpunit
  - composer install
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then ./travis-nginx-install.sh; fi"

  # Selenium
#  - "sh -e /etc/init.d/xvfb start"
#  - "export DISPLAY=:99.0"
#  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar -nv"
#  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
#  - sleep 5

script: ./vendor/bin/phpunit --group Sauce --colors Tests/