language: php
php:
  - 5.5
notifications:
  email: false
addons:
#  sauce_connect: true
#    username:
#      secure: "B9VRUWYj0GeV3bqiR6Pzs89LVwuYgrsXCeUeIY6D6YPfceD+OgjsgnuescDdUXOA12CUt075iP37IXuWOHVesx3T8BOQllltu/mXoi/tubOAnjAzaqHbgCvbSHjltTHAmZWqlghUu1jEJBHmVjV6qyq/fWPiyUL83xvv8esgod8="
#    access_key:
#      secure: "Y0lQJ4iR8X17+hcAA3K3FaZAenX09phbBibLZg3ey+OPCloLe3Rbvjl3Gfk2CfZP/utK6jnjFcEY71mqxmdDxE0KBECfx5ORp0OzGDODaAE9qAzqWwsS6DlGv0t6X8B31S9GyBJVBdL28ALkJYyKxANI0UTXUmavzlrSaIGzL80="
env:
  global:
    # SAUCE
    - secure: "fwebeORlyqO1sXaOVSx7sxeAlmWr6q68RpZWSWmp5Kdu3XcfhV/v3jcH2nIpfDLkFq2rtQw1h+dRcSdHClYedDnr/Vp9fKMkscroNWTn+QqYAJtZTWZIDs3B0B+Ea3wNc1chN7iOXdr2wrz+aX7fyw8olSoEz/+lTBNnJEJovlM="
    - secure: "jlcxYPI1ndqrAV/+IVzFf/BtL0W0oxnFAgl52wFkkgH8c2DHG8Cf2vIF7JVZs0+fhjamuyAiLO9dktowSaWA/SXXbZIBap+DKPpHCp3gjGfXlLF1wwUTT+m5PAMtsoHCs4m3yjTdyAH/Foa8uEbkcZ+mdLEjrcQV8ZxosTSl1jk="
  matrix:
    - TEST_GROUP=Smoke
    - TEST_GROUP=Sauce
before_script:
  - mysql -e 'create database ip_test;'
  - sed -e 's/\[\[\[\[database\]\]\]\]/ip_test/g' < Ip/Internal/Install/sql/structure.sql | sed -e 's/`ip_cms_/`ip_/g' | mysql -D ip_test # replace ip_cms_ and [[[[database]]]]
  - sed -e 's/`ip_cms_/`ip_/g' < Ip/Internal/Install/sql/data.sql | mysql -D ip_test # replace ip_cms_ to ip_
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u travis # ImpressPages does not allow empty db password
  - cd phpunit
  - composer install
#  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then ./travis-nginx-install.sh; fi"
  - ./travis-nginx-install.sh
  - sh -c "if [ $TEST_GROUP = "Sauce" ]; then curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash; fi"

  # Selenium
#  - "sh -e /etc/init.d/xvfb start"
#  - "export DISPLAY=:99.0"
#  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar -nv"
#  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
#  - sleep 5

script: ./vendor/bin/phpunit --group $TEST_GROUP --colors Tests/