branches:
  only:
    - evolution
    - develop
    - /^feature-.*$/
language: php
php:
  - 5.3
notifications:
  email: false
before_script:
  - mysql -e 'create database ip_test;'
  - sed -e 's/\[\[\[\[database\]\]\]\]/ip_test/g' < install/sql/structure.sql | mysql
  - mysql < install/sql/data.sql
  - cd phpunit
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then ./travis-nginx-install.sh; fi"

  # Selenium
#  - "sh -e /etc/init.d/xvfb start"
#  - "export DISPLAY=:99.0"
#  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar -nv"
#  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
#  - sleep 5

script: ./vendor/bin/phpunit --exclude-group ignoreOnTravis --colors Tests/